-- Clean dependent data and sites
DO $$ BEGIN
  IF EXISTS (
    SELECT 1 FROM information_schema.tables 
    WHERE table_schema='public' AND table_name='workflow_audit_logs'
  ) THEN
    TRUNCATE TABLE public.workflow_audit_logs;
  END IF;
END $$;

-- Site assignments do not have FKs, but clear to avoid orphans
TRUNCATE TABLE public.site_assignments;

-- Now clear all sites
TRUNCATE TABLE public.sites;

-- Insert exactly 7 sites with different statuses
INSERT INTO public.sites (
  id,
  name,
  organization_id,
  organization_name,
  organization_logo,
  location,
  address,
  postcode,
  status,
  target_live_date,
  assigned_ops_manager,
  assigned_deployment_engineer,
  sector,
  unit_code,
  criticality_level,
  stakeholders,
  created_at,
  updated_at,
  is_archived
) VALUES
(
  gen_random_uuid(),
  'ASDA Redditch',
  NULL,
  'ASDA',
  NULL,
  'Redditch',
  'High Street, Redditch',
  'B97 4EH',
  'site_created',
  '2025-11-15',
  'Sarah Johnson',
  'Mike Wilson',
  'Retail',
  'ASDA-RD-001',
  'high',
  '[]'::jsonb,
  now(),
  now(),
  false
),
(
  gen_random_uuid(),
  'Tesco Birmingham',
  NULL,
  'Tesco',
  NULL,
  'Birmingham',
  'New Street, Birmingham',
  'B2 4QA',
  'site_study_done',
  '2025-12-01',
  'John Smith',
  'Emma Davis',
  'Retail',
  'TESCO-BM-002',
  'medium',
  '[]'::jsonb,
  now(),
  now(),
  false
),
(
  gen_random_uuid(),
  'Sainsbury Manchester',
  NULL,
  'Sainsbury',
  NULL,
  'Manchester',
  'Market Street, Manchester',
  'M1 1WS',
  'scoping_done',
  '2025-10-20',
  'Alice Brown',
  'Tom Wilson',
  'Retail',
  'SAINS-MC-003',
  'high',
  '[]'::jsonb,
  now(),
  now(),
  false
),
(
  gen_random_uuid(),
  'Morrisons Leeds',
  NULL,
  'Morrisons',
  NULL,
  'Leeds',
  'Briggate, Leeds',
  'LS1 6HB',
  'approved',
  '2025-11-30',
  'David Lee',
  'Sophie Clark',
  'Retail',
  'MORR-LD-004',
  'medium',
  '[]'::jsonb,
  now(),
  now(),
  false
),
(
  gen_random_uuid(),
  'ASDA Liverpool',
  NULL,
  'ASDA',
  NULL,
  'Liverpool',
  'Lord Street, Liverpool',
  'L2 5UZ',
  'procurement_done',
  '2025-10-15',
  'Rachel Green',
  'Chris Martin',
  'Retail',
  'ASDA-LV-005',
  'high',
  '[]'::jsonb,
  now(),
  now(),
  false
),
(
  gen_random_uuid(),
  'Tesco London Central',
  NULL,
  'Tesco',
  NULL,
  'London',
  'Oxford Street, London',
  'W1A 0AB',
  'deployed',
  '2025-10-05',
  'Mark Thompson',
  'Lisa Anderson',
  'Retail',
  'TESCO-LC-006',
  'high',
  '[]'::jsonb,
  now(),
  now(),
  false
),
(
  gen_random_uuid(),
  'Sainsbury Bristol',
  NULL,
  'Sainsbury',
  NULL,
  'Bristol',
  'Cabot Circus, Bristol',
  'BS1 3BN',
  'live',
  '2025-09-25',
  'Jennifer White',
  'Robert Taylor',
  'Retail',
  'SAINS-BR-007',
  'medium',
  '[]'::jsonb,
  now(),
  now(),
  false
);
