-- Clear existing sites and related data
DELETE FROM sites;
DELETE FROM site_assignments;

-- Insert 7 sites with different statuses
INSERT INTO sites (
  id,
  name,
  address,
  organization_id,
  status,
  target_live_date,
  assigned_ops_manager,
  assigned_deployment_engineer,
  sector,
  unit_code,
  description,
  created_at,
  updated_at
) VALUES 
(
  gen_random_uuid(),
  'ASDA Redditch',
  'High Street, Redditch, B97 4EH',
  (SELECT id FROM organizations WHERE name ILIKE '%ASDA%' LIMIT 1),
  'site_created',
  '2025-11-15',
  'Sarah Johnson',
  'Mike Wilson',
  'Retail',
  'ASDA-RD-001',
  'Primary ASDA location in Redditch',
  '2025-09-01',
  '2025-09-01'
),
(
  gen_random_uuid(),
  'Tesco Birmingham',
  'New Street, Birmingham, B2 4QA',
  (SELECT id FROM organizations WHERE name ILIKE '%Tesco%' LIMIT 1),
  'site_study_done',
  '2025-12-01',
  'John Smith',
  'Emma Davis',
  'Retail',
  'TESCO-BM-002',
  'Major Tesco store in Birmingham',
  '2025-09-05',
  '2025-09-05'
),
(
  gen_random_uuid(),
  'Sainsbury Manchester',
  'Market Street, Manchester, M1 1WS',
  (SELECT id FROM organizations WHERE name ILIKE '%Sainsbury%' LIMIT 1),
  'scoping_done',
  '2025-10-20',
  'Alice Brown',
  'Tom Wilson',
  'Retail',
  'SAINS-MC-003',
  'Sainsbury superstore in Manchester',
  '2025-09-10',
  '2025-09-10'
),
(
  gen_random_uuid(),
  'Morrisons Leeds',
  'Briggate, Leeds, LS1 6HB',
  (SELECT id FROM organizations WHERE name ILIKE '%Morrisons%' LIMIT 1),
  'approved',
  '2025-11-30',
  'David Lee',
  'Sophie Clark',
  'Retail',
  'MORR-LD-004',
  'Morrisons supermarket in Leeds',
  '2025-09-12',
  '2025-09-12'
),
(
  gen_random_uuid(),
  'ASDA Liverpool',
  'Lord Street, Liverpool, L2 5UZ',
  (SELECT id FROM organizations WHERE name ILIKE '%ASDA%' LIMIT 1),
  'procurement_done',
  '2025-10-15',
  'Rachel Green',
  'Chris Martin',
  'Retail',
  'ASDA-LV-005',
  'ASDA superstore in Liverpool',
  '2025-09-15',
  '2025-09-15'
),
(
  gen_random_uuid(),
  'Tesco London Central',
  'Oxford Street, London, W1A 0AB',
  (SELECT id FROM organizations WHERE name ILIKE '%Tesco%' LIMIT 1),
  'deployed',
  '2025-10-05',
  'Mark Thompson',
  'Lisa Anderson',
  'Retail',
  'TESCO-LC-006',
  'Central London Tesco Metro',
  '2025-09-18',
  '2025-09-18'
),
(
  gen_random_uuid(),
  'Sainsbury Bristol',
  'Cabot Circus, Bristol, BS1 3BN',
  (SELECT id FROM organizations WHERE name ILIKE '%Sainsbury%' LIMIT 1),
  'live',
  '2025-09-25',
  'Jennifer White',
  'Robert Taylor',
  'Retail',
  'SAINS-BR-007',
  'Sainsbury store in Bristol',
  '2025-09-20',
  '2025-09-20'
);