// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from '@/types/database';

// Supabase configuration - use environment variables with fallbacks for production
const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL || "https://ngzvoekvwgjinagdvdhf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_ANON_KEY || "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5nenZvZWt2d2dqaW5hZ2R2ZGhmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM3NzE1MzksImV4cCI6MjA2OTM0NzUzOX0.uYNZPJvpIRVBQYrP1JilauuF2evR-vgvSNp3RnnWHGw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
    storageKey: 'smartq-launchpad-auth',
    detectSessionInUrl: true,
    flowType: 'pkce',
    // Improved refresh configuration for better reliability
    refreshTokenRetryAttempts: 3, // Reduced back to 3 to avoid lock conflicts
    refreshTokenRetryDelay: 2000, // Increased back to 2000ms for stability
    // Add session timeout handling
    sessionTimeout: 30 * 24 * 60 * 60 * 1000, // 30 days
    // Enable debug mode in development
    debug: import.meta.env.DEV,
    // Add lock timeout to prevent hanging
    lockTimeout: 10000, // 10 seconds lock timeout
    // Add better error handling for cross-device access
    skipBrowserSessionCheck: false, // Ensure browser session is checked
    // Add retry configuration for initial session
    retryDelay: 1000, // 1 second delay between retries
    maxRetries: 3 // Maximum retries for session operations
  },
  db: {
    schema: 'public'
  },
  // Optimized realtime configuration - reduced for better performance
  realtime: {
    params: {
      eventsPerSecond: 5 // Reduced from 10 to 5
    }
  },
  // Add global configuration for better performance
  global: {
    headers: {
      'X-Client-Info': 'smartq-launchpad-web'
    }
  }
});

// Add error handling and performance monitoring
supabase.auth.onAuthStateChange((event, session) => {
  console.log('🔍 Auth state change:', event, session ? 'Session exists' : 'No session');
  
  if (event === 'SIGNED_OUT') {
    // Clear any cached data on sign out
    localStorage.removeItem('smartq-launchpad-auth');
    console.log('🧹 Cleared auth data on sign out');
  } else if (event === 'TOKEN_REFRESHED') {
    console.log('✅ Token refreshed successfully');
  } else if (event === 'SIGNED_IN') {
    console.log('✅ User signed in successfully');
  }
});

// Add periodic session health check to prevent expiration
if (typeof window !== 'undefined') {
  setInterval(async () => {
    try {
      const { data: { session } } = await supabase.auth.getSession();
      if (session) {
        const now = Date.now();
        const expiresAt = session.expires_at ? session.expires_at * 1000 : 0;
        const timeUntilExpiry = expiresAt - now;
        
        // If session expires in less than 5 minutes, try to refresh
        if (timeUntilExpiry < 5 * 60 * 1000 && timeUntilExpiry > 0) {
          console.log('⚠️ Session expires soon, attempting refresh...');
          await supabase.auth.refreshSession();
        }
      }
    } catch (error) {
      console.warn('⚠️ Periodic session check failed:', error);
    }
  }, 60000); // Check every minute
}

// Session initialization helper for better cross-device handling
export const initializeSession = async () => {
  try {
    console.log('🔄 Initializing session...');
    
    // First, try to get existing session
    const { data: { session }, error } = await supabase.auth.getSession();
    
    if (error) {
      console.warn('⚠️ Session check error:', error.message);
      
      // If there's an error, try to clear any corrupted session data
      try {
        await supabase.auth.signOut();
        console.log('🧹 Cleared corrupted session data');
      } catch (clearError) {
        console.warn('⚠️ Failed to clear session:', clearError);
      }
      
      return { session: null, error: null };
    }
    
    if (session) {
      console.log('✅ Found existing session');
      return { session, error: null };
    }
    
    console.log('ℹ️ No existing session found - user needs to authenticate');
    console.log('🔄 This is normal for new devices or after clearing browser data');
    return { session: null, error: null };
    
  } catch (error) {
    console.error('❌ Session initialization failed:', error);
    return { session: null, error: error as Error };
  }
};